<?php 

$catBreeds = [
    "Siamese cat",
    "British Shorthair",
    "Maine Coon",
    "Persian cat",
    "Ragdoll",
    "Sphynx cat",
    "American Shorthair",
    "Abyssinian",
    "Exotic Shorthair",
    "Scottish Fold",
    "Burmese cat",
    "Birman",
    "Bombay cat",
    "Russian Blue",
    "Siberian cat",
    "Norwegian Forest cat",
    "Munchkin cat",
    "American Curl",
    "American Bobtail",
    "Balinese cat",
    "Oriental Shorthair",
    "Devon Rex",
    "Chartreux",
    "Turkish Angora",
    "Japanese Bobtail",
    "Manx Cat",
    "American Wirehair",
    "Ragamuffin",
    "Somali cat",
    "Egyptian Mau",
    "Himalayan cat",
    "Cornish Rex",
    "Selkirk Rex",
    "Tonkinese cat",
    "Singapura cat",
    "Ocicat",
    "Korat",
    "Turkish Van",
    "British Longhair",
    "LaPerm",
    "Havana Brown",
    "Chausie",
    "Burmilla",
    "Colorpoint Shorthair",
    "Toyger",
    "Sokoke",
    "Javanese cat",
    "Snowshoe cat",
    "Australian Mist",
    "Lykoi",
    "Khao Manee"
];

sort($catBreeds, SORT_STRING);
